MOHC-LTD/httpshopify

addresses.go
go.mod
go.sum
orders.go

Co-authored-by: Harry Withers <harryw@mohc.net>

Order Addresses

---

addresses.go
go.mod
go.sum

Co-authored-by: Harry Withers <harryw@mohc.net>

Lat and Long fix

---

go.mod
go.sum
shop.go
variants.go

* chore: updating shopify package
* feat: adding variants to shop implementation
* feat: adding variants get implementation
Co-authored-by: Harry <63407848+harry-mohc@users.noreply.github.com>

feat: variants (#9)

---

go.mod
go.sum
inventory-levels.go
shop.go

* feat: update shopify
* feat: inventory levels

Inventory levels

---

.githooks/pre-commit
.githooks/pre-push
go.mod
go.sum
line-items.go
money.go
price-set.go
shipping.go
tax-line.go

* feat: add prices to DTOs
* feat: add code to convert new fields and structs to shopify domain
* fix: use bash
* docs: add comments to exports

feat: add cost fields (#17)

---

README.md
go.mod
go.sum
internal/http/client.go
internal/http/delete.go
internal/http/get.go
internal/http/headers.go
internal/http/options.go
internal/http/post.go
internal/http/put.go
internal/http/rates.go
internal/http/status.go
rates.go
shop.go

* reactor: http package to use single method base
* feat: rate limited http client
* refactor: make default headers an option
* feat: rates
* feat: shopify rate limits
* fix: print error body for now
* docs: rate limit docs

Rate limits

---

go.mod
go.sum
products.go

* chore: bump shopify
* feat: get product

Get product

---

collections.go
collections_test.go
customers.go
customers_test.go
fulfillment-events.go
fulfillment-events_test.go
fulfillments.go
fulfillments_test.go
images.go
images_test.go
inventory-levels.go
inventory-levels_test.go
orders.go
orders_test.go
product-images.go
product-images_test.go
products.go
products_test.go
variants.go
variants_test.go

* fix: checking if dates are set
* refactor: adding checks before assigning to shopify package
* refactor: adding pointer checks
* refactor: adding better pointer checks
* fix: fixing bugs from tests
* test: adding tests for date fields
Co-authored-by: Ianmohc <63408186+Ianmohc@users.noreply.github.com>

Omitting empty time fields

---

go.mod
go.sum
variants.go

* feat: inventory quantity on variants
* chore: bump shopify version

Inventory quantity

---

discounts.go
go.mod
go.sum
line-items.go
orders.go
variants.go

…e (#56)
* feat: discount allocations, applications
* fix: discount application json tag
* fix: compare at price json tag
* docs: discount methods and types

feat: discount applications, allocations, and compare at price (#56)

---

go.mod
go.sum
orders.go

* feat: handle note attributes in the order dto
* fix: comments

feat: add note attributes to order dto (#58)

---

fulfillments.go
go.mod
go.sum
orders.go

feat: add company tracking company and urls to fulfilment update

feat(SHOPIFY-336): add company tracking company and urls to fulfilment update

---

fulfillments.go
go.mod
go.sum
orders.go

Attempt to fix some issues when comparing develop branch to main and seeing differences when no difference should be showing

Merge main into develop

---

go.mod
go.sum
products.go
variants.go

* feat: adding product update functionality
* ci: updating shopify version to v1.24.0
* refactor: changing to updateDTO
* refactor: changing the "correct" createDTO to updateDTO

feat: adding product update functionality (#70)

---

go.mod
go.sum
metafields.go
shop.go

* feat: adding metafields list functionality
* ci: upgrading shopify version
* refactor: metafield was one word
* refactor: not using the complex types now. Just strings.
Co-authored-by: connor-mohc <66954210+connor-mohc@users.noreply.github.com>
Co-authored-by: Karl <85934470+karlmohc@users.noreply.github.com>

feat: Adding metafields list functionality (#69)

---

customers.go
go.mod
go.sum
shop.go

* feat: adding customers implementation
* feat: adding the customers implementation to the shop
* feat: adding customer errors
* ci: updating shopify version
* refactor: customer errors better
* refactor: go mod update
* ci: updating shopify package to v1.26.0

feature: SHP-300 Customer update (#68)

---

customers.go
go.mod
go.sum

* feat: adding customers implementation
* feat: adding the customers implementation to the shop
* feat: adding customer errors
* ci: updating shopify version
* refactor: customer errors better
* refactor: go mod update
* feat: added get customer implementation
* feat: added tags field to customer dto
* ci: updating shopify package to v1.26.0
* refactor: using tags type
* ci: upgrading shopify package to v.1.27.0
Co-authored-by: Ianmohc <ian@mohc.net>

feat: added get customer implementation (#78)

---

go.mod
go.sum
orders.go

* Allowing the update of an order
* Creating meta fields on an order
* Updating meta fields on an order
* The ability to open an order

New Features for order manipulation

---

customers.go
go.mod
go.sum

* feat: implemented get customer by query fn
* ci: bumped shopify package version

feat: get customer by query params (#90)

---

addresses.go
customers.go
go.mod
go.sum

This PR cannot be merged until a new release of the `shopify` package is released with the following changes:
- https://github.com/MOHC-LTD/shopify/pull/102

feat: customer addresses are returned in customer object

---

addresses.go
customers.go
go.mod
go.sum

* feat: customer addresses returned in customer object
* feat: bump up shopify package version

feat: customer addresses are returned in customer object (#98)

---

customer-address.go
go.mod
go.sum

Adds ability to set a default address for a customer

feat: set customer default address

---

customer-address.go
go.mod
go.sum

* feat: set customer default address
* chore: bump up shopify

feat: set customer default address (#107)

---

go.mod
go.sum
metafields.go
products.go

Adding product metafields on product creation.

feat: product metafields

---

go.mod
go.sum
shop.go
webhooks.go
webhooks_test.go

Added implementation for the Webhook resource: [See Shopify](https://shopify.dev/docs/api/admin-rest/2023-10/resources/webhook)

feat: webhook resource implementation
